language: cpp
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - protobuf-compiler
before_install:
  - source <(curl -SLs https://raw.githubusercontent.com/adafruit/travis-ci-arduino/master/install.sh)
script:
 - pushd src/Continuous-Meter-Reader && make && popd
 - pushd src/RadioStation && make && popd
 - pushd test && make && popd
 #- ./script/travis_format_checcker.sh
