language: cpp
compiler:
  - gcc
sudo: false
addons:
  apt:
    packages:
    - protobuf-compiler
    - arduino
script:
 - pushd src/Continuous-Meter-Reader && make && popd
 - pushd src/RadioStation && make && popd
 - pushd test && make && popd
 #- ./script/travis_format_checcker.sh
