language: cpp
compiler:
  - gcc
sudo: required
dist: trusty
git:
  submodules: false
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install protobuf-compiler gcc-avr avr-libc arduino
script:
 - cd $TRAVIS_BUILD_DIR/src/Continuous-Meter-Reader && make
 - cd $TRAVIS_BUILD_DIR/src/RadioStation && make
 - cd $TRAVIS_BUILD_DIR/test && make
 #- ./script/travis_format_checcker.sh
